/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:53ea6caf-7c9a-48d7-9fa8-ca9ba20a86df",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_V6wvYrLEF",
    "aws_user_pools_web_client_id": "2032s8h0b4900pa8urjinj7eg7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "region": "eu-central-1",
    "userPoolId": "eu-central-1_V6wvYrLEF",
    "userPoolWebClientId": "2032s8h0b4900pa8urjinj7eg7",
    "identityPoolId": "eu-central-1:c368c0b4-fbed-49cd-9a9e-b1d678ab1de1"
};


export default awsmobile;
