/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:c368c0b4-fbed-49cd-9a9e-b1d678ab1de1",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_PrMBMwjF2",
    "aws_user_pools_web_client_id": "70gdlhn6bi6fedflsr0o3f2g2a",
    "oauth": {
        "domain": "congregation.auth.eu-central-1.amazoncognito.com"
    },
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "GIVEN_NAME",
        "FAMILY_NAME",
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "region": "eu-central-1",
    "userPoolId": "eu-central-1_PrMBMwjF2",
    "userPoolWebClientId": "70gdlhn6bi6fedflsr0o3f2g2a",
    "identityPoolId": "eu-central-1:c368c0b4-fbed-49cd-9a9e-b1d678ab1de1",
     "cookieStorage": {
      // REQUIRED - Cookie domain (only required if cookieStorage is provided)
      "domain": '.markus-mildner.dev',
      // OPTIONAL - Cookie path
      "path": '/',
      // OPTIONAL - Cookie expiration in days
      "expires": 365,
      // OPTIONAL - Cookie secure flag
      // Either true or false, indicating if the cookie transmission requires a secure protocol (https).
      "secure": false,
    },
};


export default awsmobile;
